# Generated by Django 3.0.2 on 2020-01-29 18:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa kategori', max_length=200, unique=True, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Delivery_memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Descent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descent_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['descent_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pełna nazwa produktu', max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('kind', models.CharField(help_text='Typ produktu', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Category')),
            ],
            options={
                'ordering': ['name', 'quantity', 'price', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('products', models.ManyToManyField(through='store.Delivery_memory', to='store.Product')),
            ],
            options={
                'ordering': ['supply_date'],
            },
        ),
        migrations.CreateModel(
            name='Descent_memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('descent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Descent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
        migrations.AddField(
            model_name='descent',
            name='products',
            field=models.ManyToManyField(through='store.Descent_memory', to='store.Product'),
        ),
        migrations.AddField(
            model_name='delivery_memory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
        migrations.AddField(
            model_name='delivery_memory',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Supply'),
        ),
    ]
